/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/idMDAEmG0sv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Guest() {
  return (
    <main className="w-full max-w-4xl mx-auto px-4 py-12 md:px-6 md:py-16">
      <div className="space-y-6">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-[#4B0082] mb-2">Welcome to Our Guestbook!</h1>
          <p className="text-gray-600 dark:text-gray-400 text-lg">
            Please take a moment to sign our guestbook and share your thoughts.
          </p>
        </div>
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg">
          <form className="space-y-4">
            <div>
              <label className="block text-gray-700 dark:text-gray-300 font-medium mb-1" htmlFor="name">
                Name
              </label>
              <input
                className="w-full px-4 py-3 rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-[#9370DB] focus:border-transparent"
                id="name"
                placeholder="Enter your name"
                type="text"
              />
            </div>
            <div>
              <label className="block text-gray-700 dark:text-gray-300 font-medium mb-1" htmlFor="message">
                Message
              </label>
              <textarea
                className="w-full px-4 py-3 rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-[#9370DB] focus:border-transparent"
                id="message"
                placeholder="Share your thoughts..."
                rows={4}
              />
            </div>
            <button
              className="w-full bg-[#9370DB] hover:bg-[#8258FA] text-white font-medium py-3 px-6 rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-[#8258FA] focus:border-transparent"
              type="submit"
            >
              Submit
            </button>
          </form>
        </div>
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg max-h-[400px] overflow-y-auto">
          <h2 className="text-2xl font-bold text-[#4B0082] mb-4">Guestbook Entries</h2>
          <div className="space-y-4">
            <div className="bg-[#F0F8FF] dark:bg-[#1F1F1F] p-4 rounded-lg shadow-md">
              <p className="text-[#4B0082] font-bold text-lg">John Doe</p>
              <p className="text-gray-600 dark:text-gray-400 text-base">
                This is a wonderful guestbook! I had a great time visiting your website.
              </p>
            </div>
            <div className="bg-[#FFF0F5] dark:bg-[#1F1F1F] p-4 rounded-lg shadow-md">
              <p className="text-[#FF69B4] font-bold text-lg">Jane Smith</p>
              <p className="text-gray-600 dark:text-gray-400 text-base">
                I love the vibrant colors and creative design of this guestbook. Keep up the great work!
              </p>
            </div>
            <div className="bg-[#E6E6FA] dark:bg-[#1F1F1F] p-4 rounded-lg shadow-md">
              <p className="text-[#8B008B] font-bold text-lg">Michael Johnson</p>
              <p className="text-gray-600 dark:text-gray-400 text-base">
                This is the coolest guestbook I've ever seen. I can't wait to come back and sign it again!
              </p>
            </div>
            <div className="bg-[#FFEFD5] dark:bg-[#1F1F1F] p-4 rounded-lg shadow-md">
              <p className="text-[#CD853F] font-bold text-lg">Emily Davis</p>
              <p className="text-gray-600 dark:text-gray-400 text-base">
                Wow, this guestbook is so much fun! I love the vibrant colors and unique design.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
